#+latex_class: cv
#+options: title:nil toc:nil

#+begin_export latex
\begin{center}
{\scshape\huge Julian Grove}
\end{center}
\vspace{5mm}
#+end_export

* Contact Information
  #+begin_export latex
\begin{tabular}{@{} m{0.085\textwidth} m{0.4\textwidth} m{0.085\textwidth} m{0.4\textwidth}}
    \textsc{Address:}&\oldstylenums{507} Lattimore Hall & \textsc{Email} & \href{mailto:julian.grove@gmail.com}{julian.grove@gmail.com} \\
    & Department of Linguistics & \textsc{Web} & \href{http://juliangrove.github.io}{juliangrove.github.io} \\
    & University of Rochester & \textsc{GitHub} & \href{http://github.com/juliangrove}{juliangrove} \\
    & 500 Joseph C. Wilson Blvd. \\
    & Rochester, NY \oldstylenums{14627} \\
    & United States
\end{tabular}
  #+end_export

* Employment
  #+begin_export latex
\begin{tabular}{@{}b{0.12\textwidth}@{}p{0.88\textwidth}}
\oldstylenums{2022\textendash } & \textbf{The University of Rochester}\\
& Post-doctoral researcher \\
& FACTS.lab (directed by Aaron Steven White) \\
& Department of Linguistics \\
\oldstylenums{2020\textendash 2022}& \textbf{The University of Gothenburg} \\
& Post-doctoral researcher \\
& Centre for Linguistic Theory and Studies in Probability \\
& Department of Philosophy, Linguistics and Theory of Science \\
\end{tabular}
  #+end_export

* Education
  #+begin_export latex
\begin{tabular}{@{}b{0.12\textwidth}@{}p{0.88\textwidth}}
\oldstylenums{2012\textendash 2019} & \textbf{The University of Chicago}\\
& PhD in Linguistics \\
& \emph{Thesis:} \href{https://semanticsarchive.net/Archive/TRmOTkzM/}{Scope-taking and presupposition satisfaction} \\
& \emph{Committee:} Chris Kennedy (chair), Itamar Francez, Greg Kobele, and Malte Willer \\
\oldstylenums{2006\textendash 2010} & \textbf{Johns Hopkins University} \\
& BA (with general and departmental honors) in Cognitive Science
\end{tabular}
  #+end_export

* Publications
** Published papers
   #+begin_export latex
\begin{tabular}{@{}b{0.15\textwidth}@{}p{0.85\textwidth}}
\oldstylenums{2023} & \textbf{Julian Grove} \& Jean-Philippe Bernardy. Probabilistic compositional semantic, purely. \textit{New Frontiers in Artificial Intelligence}. \textit{JSAI-isAI 2021}. \textsc{doi}:\href{http://doi.org/10.1007/978-3-031-36190-6_17}{10.1007/978-3-031-36190-6\_17}. \\
\oldstylenums{2023} & \textbf{Julian Grove} \& Jean-Philippe Bernardy. Algebraic effects for extensible dynamic semantics. In \textit{Journal of Logic, Language and Information}. 32:219--245. \textsc{doi}:\href{http://doi.org/10.1007/s10849-022-09378-7}{10.1007/s10849-022-09378-7}. \\
\oldstylenums{2022} & \textbf{Julian Grove}. An alternative semantics for presupposition. Proceedings of the Amsterdam Colloquium 2022. Available on \href{https://ling.auf.net/lingbuzz/006976}{LingBuzz}. \\
\oldstylenums{2022} & \textbf{Julian Grove}. Presupposition projection as a scope phenomenon. In \textit{Semantics and Pragmatics} 15(15). \textsc{doi}:\href{http://doi.org/10.3765/sp.15.15}{10.3765/sp.15.15}. \\
\oldstylenums{2022} & Jean-Philippe Bernardy, \textbf{Julian Grove}, \& Christine Howes. Rational Speech Act models are utterance-independent updates of world priors. Proceedings of the 26th Workshop on the Semantics and Pragmatics of Dialogue. Available in the \href{http://semdial.org/anthology/papers/Z/Z22/Z22-3013}{ACL Anthology}. \\
\oldstylenums{2021} & \textbf{Julian Grove}, Jean-Philippe Bernardy, \& Stergios Chatzikyriakidis. From compositional semantics to Bayesian pragmatics via logical inference. Proceed ings of Natural Logic Meets Machine Learning II, Workshop @IWCS. Published by the Association for Computational Linguistics. Available in the \href{https://aclanthology.org/2021.naloma-1.8}{ACL Anthology}. \\
\oldstylenums{2019} & Ming Xiang, \textbf{Julian Grove}, \& Jason Merchant. Structural priming in production through ‘silence’: An investigation of verb phrase ellipsis and null complement anaphora. In \textit{Glossa: a journal of general linguistics} 4(1): 67. \textsc{doi}:\href{http://doi.org/10.5334/gjgl.726}{10.5334/gjgl.726}.
\end{tabular}
\begin{tabular}{@{}b{0.15\textwidth}@{}p{0.85\textwidth}}
\oldstylenums{2017} & Emily Hanink \& \textbf{Julian Grove}. German relative clauses and the severed-index hypothesis. In Proceedings of the 34th annual meeting of the West Coast Conference on Formal Linguistics, ed. Aaron Kaplan, et al., 241-248, Somerville, MA: Cascadilla Proceedings Project. \\
\oldstylenums{2016} & Ming Xiang, \textbf{Julian Grove}, \& Anastasia Giannakidou. Semantic and pragmatic processes in the comprehension of negation: an event related potential study of negative polarity sensitivity. In \textit{Journal of Neurolinguistics} 38:71--88. \textsc{doi}:\href{https://doi.org/10.1016/j.jneuroling.2015.11.001}{10.1016/j.jneuroling.2015.11.001}. \\
\oldstylenums{2016} & \textbf{Julian Grove} \& Emily Hanink. Article selection and anaphora in the German relative clause. Proceedings of the 26th annual meeting of Semantics and Linguistic Theory, ed. Mary Maroney, Carol-Rose Little, Jacob Collard, and Dan Burgdorf, 417--432. Ithaca, NY: Cornell. \\
\oldstylenums{2015} & \textbf{Julian Grove}. Singular count pseudo-partitives. In Proceedings of Sinn und Bedeutung 19, 248--265. \\
\oldstylenums{2014} & \textbf{Julian Grove}. The lexical semantics of much: conversion from intervals to degrees. Proceedings of the 44th Annual Meeting of the North Eastern Linguistic Society. \\
\oldstylenums{2013} & Ming Xiang, \textbf{Julian Grove}, \& Anastasia Giannakidou. Dependency-dependent interference: NPI interference, agreement attraction, and global pragmatic inferences. In \textit{Frontiers in Psychology} 4(708). \textsc{doi}:\href{http://doi.org/10.3389/fpsyg.2013.00708}{10.3389/fpsyg.2013.00708}. \\
\oldstylenums{2011} & Carissa Abrego-Collier, \textbf{Julian Grove}, Morgan Sonderegger, \& Alan Yu. Effects of speaker evaluation on phonetic convergence. Proceedings of the 17th International Congress of Phonetic Sciences. \\
\oldstylenums{2011} & Alan Yu, \textbf{Julian Grove}, Martina Martinović, \& Morgan Sonderegger. Effects of working working memory capacity and “autistic traits” on phonotactic effects in speech perception. Proceedings of the 17th International Congress of Phonetic Sciences
\end{tabular}
   #+end_export

** Papers in progress
   #+begin_export latex
\begin{tabular}{@{}b{0.15\textwidth}@{}p{0.85\textwidth}}
Submitted & \textbf{Julian Grove} \& Aaron Steven White. Factivity, presupposition projection, and the role of discrete knowledge in gradient inference judgments. Draft available on \href{https://ling.auf.net/lingbuzz/007450}{LingBuzz}. \\
Submitted & Jean-Philippe Bernardy, \textbf{Julian Grove}, and Chris Howes. The informative speech act.
\end{tabular}
   #+end_export
